DATA_PATH = "data/"

BASE_URL = "https://www.fantasypros.com"
RANKINGS_URL = BASE_URL + "/nfl/rankings/{}-cheatsheets.php?filters=f3bc15d83d"
STATS_URL = BASE_URL + "/nfl/stats/{}.php"
MISSING_PHOTO_URL = "https://images.fantasypros.com/images/photo_missing_square.jpg"
LOGIN_URL = "https://secure.fantasypros.com/accounts/login/?next=https://www.fantasypros.com/"

DB_ENGINE = "postgresql://mengeling:mengeling@localhost:5432/ffball"

BIO_HEADERS = ["id", "height", "weight", "age", "college"]
RANKINGS_HEADERS = [
    "id",
    "rank",
    "name",
    "bio_url",
    "team",
    "position",
    "position_ranking",
    "bye_week",
    "best_ranking",
    "worst_ranking",
    "avg_ranking",
    "std_dev_ranking",
    "avg_draft_pick",
]
STATS_ALL_HEADERS = [
    "id",
    "fantasy_pts",
    "position",
    "pass_cmp",
    "pass_att",
    "pass_yds",
    "pass_td",
    "pass_int",
    "rush_att",
    "rush_yds",
    "rush_td",
    "receptions",
    "rec_yds",
    "rec_td"
]
STATS_HEADERS = {
    "qb": [
        "id",
        "pass_cmp",
        "pass_att",
        "pass_cmp_pct",
        "pass_yds",
        "pass_yds_per_att",
        "pass_td",
        "pass_int",
        "pass_sacks",
        "rush_att",
        "rush_yds",
        "rush_td",
        "fumbles",
        "games",
        "fantasy_pts",
        "fantasy_pts_per_game",
    ],
    "rb": [
        "id",
        "rush_att",
        "rush_yds",
        "rush_yds_per_att",
        "rush_long",
        "rush_20+",
        "rush_td",
        "receptions",
        "rec_tgt",
        "rec_yds",
        "rec_yds_per_rec",
        "rec_td",
        "fumbles",
        "games",
        "fantasy_pts",
        "fantasy_pts_per_game",
    ],
    "wr": [
        "id",
        "receptions",
        "rec_tgt",
        "rec_yds",
        "rec_yds_per_rec",
        "rec_long",
        "rec_20+",
        "rec_td",
        "rush_att",
        "rush_yds",
        "rush_td",
        "fumbles",
        "games",
        "fantasy_pts",
        "fantasy_pts_per_game",
    ],
    "te": [
        "id",
        "receptions",
        "rec_tgt",
        "rec_yds",
        "rec_yds_per_rec",
        "rec_long",
        "rec_20+",
        "rec_td",
        "rush_att",
        "rush_yds",
        "rush_td",
        "fumbles",
        "games",
        "fantasy_pts",
        "fantasy_pts_per_game",
    ],
    "k": [
        "id",
        "field_goals",
        "fg_att",
        "fg_pct",
        "fg_long",
        "fg_1_19",
        "fg_20_29",
        "fg_30_39",
        "fg_40_49",
        "fg_50+",
        "extra_points",
        "xp_att",
        "games",
        "fantasy_pts",
        "fantasy_pts_per_game",
    ],
    "dst": [
        "id",
        "sacks",
        "int",
        "fumbles_recovered",
        "fumbles_forced",
        "def_td",
        "safeties",
        "special_teams_td",
        "games",
        "fantasy_pts",
        "fantasy_pts_per_game",
    ],
}
